<?php include('partials/menu.php');?>
<?php
    $apiKey = "rzp_test_q1mMC2rdf65z94";
    if(isset($_SESSION['order']))
    {
        echo $_SESSION['order'];
        unset($_SESSION['order']);
    }
?>
 <?php 
        //CHeck whether food id is set or not
        if(isset($_GET['order_id']))
        {
            //Get the Food id and details of the selected food
            $order_id = $_GET['order_id'];

            //Get the DEtails of the SElected Food
            $sql = "SELECT * FROM tbl_order WHERE id=$order_id";
            //Execute the Query
            $res = mysqli_query($conn, $sql);
            //Count the rows
            $count = mysqli_num_rows($res);
            //CHeck whether the data is available or not
            if($count==1)
            {
                //WE Have DAta
                //GEt the Data from Database
                $row = mysqli_fetch_assoc($res);

                $customer_name = $row['customer_name'];
                $customer_contact = $row['customer_contact'];
                $cutomer_email = $row['customer_email'];
                $amount = $row['total']*100;
            }
            else
            {
                
                //REdirect to Home Page
                header('location:'.SITEURL.'user/myorder.php');
            }
        }
        else
        {
            //Redirect to homepage
            header('location:'.SITEURL.'user/myorder.php');
        }

      $a=$amount;  
    ?>
                   

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="bill.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $a;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $order_id;?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="CanteenManagementSystem"
    data-description="Health is Wealth....!!!!"
    data-image="http://localhost/food-order/images/logo.png"
    data-prefill.name="<?php echo $customer_name;?>"
    data-prefill.email="<?php echo $customer_email;?>"
    data-prefill.contact="<?php echo $customer_contact;?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
<?php include('partials/footer.php');?>